version: 2

sources:
  - name: public
    schema: public
    tables:
      - name: daily_checkin
        columns:
          - name: checkin_date
            tests:
              - not_null
              - unique
      - name: caffeine_log
        columns:
          - name: caffeine_id
            tests:
              - not_null
              - unique
      - name: exercise_log
        columns:
          - name: exercise_id
            tests:
              - not_null
              - unique
